# Generated by Django 2.2 on 2020-07-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200731_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
