# Generated by Django 2.2 on 2020-09-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180426_0048'),
        ('blog', '0006_delete_readnum'),
    ]

    operations = [
    ]
