# Generated by Django 2.2 on 2020-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_merge_20200901_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
