# Generated by Django 2.2 on 2020-09-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20180426_0048'),
        ('comment', '0002_auto_20200826_1043'),
    ]

    operations = [
    ]
